/**:
  ros__parameters:
    max_range: 1.35
    max_angular: 0.15
    m_dist_threshold: 2.0
    dt: 0.1
    process_noise_v: 0.2  # m/s (std) - 20x for testing
    process_noise_w: 4.0  # rad/s (std) - 20x for testing
    measurement_noise_r: 1.0  # 20x for testing
    measurement_noise_b: 1.0  # 20x for testing
    # Starting state confidence
    state_cov_x: 0.01 # 95% within +- 20 cm
    state_cov_y: 0.01 # 95% within +- 20 cm
    state_cov_yaw: 0.01 # 95% within +- 11 degrees

