/**:
  ros__parameters:
    max_range: 1.35
    max_angular: 0.15
    m_dist_threshold: 2.0
    dt: 0.1
    process_noise_v: 0.005 #0.0025  # m/s (std) - from empirical drive tests
    process_noise_w: 0.6 #0.3  # rad/s (std) - from empirical rotation tests
    measurement_noise_r: 0.02
    measurement_noise_b: 0.02
    # Starting state confidence
    state_cov_x: 0.0001 # 95% within +- 2 cm
    state_cov_y: 0.0001 # 95% within +- 2 cm
    state_cov_yaw: 0.0003 # 95% within +- 2 degrees

