apriltags:  
  - id: 10
    # Position in map frame (meters)
    x: 1.4
    y: 0.0
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: -0.5
    qz: -0.5
    qw: 0.5
  - id: 2
    # Position in map frame (meters)
    x: 1.0
    y: 2.4
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.707
    qy: 0.0
    qz: 0.0
    qw: 0.707
  - id: 3
    # Position in map frame (meters)
    x: -0.4
    y: -0.4
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.0
    qy: 0.707
    qz: 0.707
    qw: 0.0
