%YAML:1.0
---
image_width: 1280
image_height: 720
camera_name: camera

camera_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [626.79632, 0.0, 644.56683,
         0.0, 631.71139, 303.66954,
         0.0, 0.0, 1.0]

distortion_model: plumb_bob
distortion_coefficients: !!opencv-matrix
  rows: 1
  cols: 5
  dt: d
  data: [-0.274755, 0.054932, 0.000526, 0.000454, 0.0]

rectification_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]

projection_matrix: !!opencv-matrix
  rows: 3
  cols: 4
  dt: d
  data: [430.88684, 0.0, 643.54172, 0.0,
         0.0, 559.62720, 289.38364, 0.0,
         0.0, 0.0, 1.0, 0.0]